"""
Fine-tuning pipeline integration for Saido Agent.

Manages the full fine-tuning workflow: uploading training data, starting jobs
(OpenAI cloud or local Axolotl), monitoring progress, deploying finished
models into the routing config, and A/B comparison testing.

Synthetic training data is generated by knowledge/synthetic.py (separate
module). This module consumes that data and orchestrates everything after
generation.
"""
from __future__ import annotations

import json
import logging
import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------

class FinetuneStatus(str, Enum):
    PENDING = "pending"
    UPLOADING = "uploading"
    TRAINING = "training"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


@dataclass
class FinetuneJob:
    id: str
    provider: str  # "openai" | "local"
    model_base: str
    training_file: str
    status: FinetuneStatus = FinetuneStatus.PENDING
    fine_tuned_model: str | None = None
    created_at: str = ""
    error: str | None = None
    metadata: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "provider": self.provider,
            "model_base": self.model_base,
            "training_file": self.training_file,
            "status": self.status.value,
            "fine_tuned_model": self.fine_tuned_model,
            "created_at": self.created_at,
            "error": self.error,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "FinetuneJob":
        return cls(
            id=data["id"],
            provider=data["provider"],
            model_base=data["model_base"],
            training_file=data["training_file"],
            status=FinetuneStatus(data.get("status", "pending")),
            fine_tuned_model=data.get("fine_tuned_model"),
            created_at=data.get("created_at", ""),
            error=data.get("error"),
            metadata=data.get("metadata", {}),
        )


@dataclass
class FinetuneResult:
    job: FinetuneJob
    message: str


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------

def _validate_jsonl(path: Path) -> None:
    """Validate that a file exists and contains valid JSONL with expected structure."""
    if not path.exists():
        raise FileNotFoundError(f"Training file not found: {path}")
    if path.suffix != ".jsonl":
        raise ValueError(f"Training file must be .jsonl format, got: {path.suffix}")
    with open(path, "r", encoding="utf-8") as fh:
        line_count = 0
        for i, line in enumerate(fh, 1):
            stripped = line.strip()
            if not stripped:
                continue
            try:
                obj = json.loads(stripped)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON on line {i}: {exc}") from exc
            if not isinstance(obj, dict):
                raise ValueError(f"Line {i} must be a JSON object, got {type(obj).__name__}")
            if "messages" not in obj:
                raise ValueError(f"Line {i} missing required 'messages' field")
            line_count += 1
    if line_count == 0:
        raise ValueError("Training file is empty (no valid JSONL lines)")


# ---------------------------------------------------------------------------
# OpenAI API helpers (thin wrappers so we can mock cleanly)
# ---------------------------------------------------------------------------

def _get_openai_client():
    """Return an OpenAI client, or None if the SDK is not installed / configured."""
    try:
        import openai  # noqa: F811
        return openai.OpenAI()
    except Exception:
        return None


# ---------------------------------------------------------------------------
# FinetuneManager
# ---------------------------------------------------------------------------

class FinetuneManager:
    """Orchestrates fine-tuning jobs across OpenAI and local (Axolotl) backends."""

    def __init__(
        self,
        model_router=None,
        config_dir: Path | None = None,
        openai_client=None,
    ):
        self._router = model_router
        self._config_dir = config_dir or Path.home() / ".saido_agent"
        self._jobs_file = self._config_dir / "finetune_jobs.json"
        self._models_file = self._config_dir / "models.json"
        self._openai = openai_client  # injectable for testing
        self._jobs: list[FinetuneJob] = []
        self._load_jobs()

    # -- Persistence ------------------------------------------------------------

    def _save_jobs(self) -> None:
        self._config_dir.mkdir(parents=True, exist_ok=True)
        payload = [j.to_dict() for j in self._jobs]
        self._jobs_file.write_text(
            json.dumps(payload, indent=2) + "\n", encoding="utf-8"
        )

    def _load_jobs(self) -> list[FinetuneJob]:
        if self._jobs_file.exists():
            try:
                data = json.loads(self._jobs_file.read_text(encoding="utf-8"))
                self._jobs = [FinetuneJob.from_dict(d) for d in data]
            except (json.JSONDecodeError, KeyError, OSError) as exc:
                logger.warning("Failed to load finetune jobs: %s", exc)
                self._jobs = []
        else:
            self._jobs = []
        return self._jobs

    def _find_job(self, job_id: str) -> FinetuneJob | None:
        for j in self._jobs:
            if j.id == job_id:
                return j
        return None

    # -- OpenAI fine-tuning -----------------------------------------------------

    def start_openai(
        self,
        training_file: str,
        model: str = "gpt-4o-mini-2024-07-18",
        n_epochs: int = 3,
        suffix: str | None = None,
    ) -> FinetuneResult:
        """Upload training data and start an OpenAI fine-tuning job.

        If the OpenAI SDK is not available or not configured, the job is
        created in PENDING status so the user can retry later.
        """
        path = Path(training_file)
        _validate_jsonl(path)

        job_id = f"ft-{uuid.uuid4().hex[:12]}"
        job = FinetuneJob(
            id=job_id,
            provider="openai",
            model_base=model,
            training_file=str(path.resolve()),
            status=FinetuneStatus.PENDING,
            created_at=datetime.now(timezone.utc).isoformat(),
            metadata={"n_epochs": n_epochs, "suffix": suffix},
        )

        client = self._openai or _get_openai_client()
        if client is None:
            job.status = FinetuneStatus.FAILED
            job.error = "OpenAI SDK not available or not configured"
            self._jobs.append(job)
            self._save_jobs()
            return FinetuneResult(job=job, message=job.error)

        try:
            # Upload file
            job.status = FinetuneStatus.UPLOADING
            with open(path, "rb") as fh:
                file_resp = client.files.create(file=fh, purpose="fine-tune")
            file_id = file_resp.id

            # Start fine-tuning
            job.status = FinetuneStatus.TRAINING
            ft_params: dict[str, Any] = {
                "training_file": file_id,
                "model": model,
                "hyperparameters": {"n_epochs": n_epochs},
            }
            if suffix:
                ft_params["suffix"] = suffix

            ft_resp = client.fine_tuning.jobs.create(**ft_params)
            job.metadata["openai_job_id"] = ft_resp.id
            job.metadata["openai_file_id"] = file_id

            self._jobs.append(job)
            self._save_jobs()
            return FinetuneResult(
                job=job,
                message=f"Fine-tuning job started: {ft_resp.id}",
            )

        except Exception as exc:
            job.status = FinetuneStatus.FAILED
            job.error = str(exc)
            self._jobs.append(job)
            self._save_jobs()
            return FinetuneResult(job=job, message=f"Fine-tuning failed: {exc}")

    # -- Local fine-tuning (Axolotl) -------------------------------------------

    def start_local(
        self,
        training_file: str,
        config: dict | None = None,
    ) -> FinetuneResult:
        """Generate an Axolotl YAML config for local fine-tuning.

        The user (or an external script) runs the actual training; this
        method only sets up the config and bookkeeping.
        """
        path = Path(training_file)
        _validate_jsonl(path)

        job_id = f"ft-local-{uuid.uuid4().hex[:12]}"
        cfg = config or {}

        base_model = cfg.get("base_model", "mistralai/Mistral-7B-v0.1")
        output_dir = self._config_dir / "finetune" / job_id
        output_dir.mkdir(parents=True, exist_ok=True)

        axolotl_config = {
            "base_model": base_model,
            "model_type": cfg.get("model_type", "MistralForCausalLM"),
            "tokenizer_type": cfg.get("tokenizer_type", "LlamaTokenizer"),
            "load_in_8bit": cfg.get("load_in_8bit", True),
            "datasets": [
                {
                    "path": str(path.resolve()),
                    "type": "sharegpt",
                }
            ],
            "adapter": cfg.get("adapter", "lora"),
            "lora_r": cfg.get("lora_r", 16),
            "lora_alpha": cfg.get("lora_alpha", 32),
            "lora_dropout": cfg.get("lora_dropout", 0.05),
            "lora_target_modules": cfg.get(
                "lora_target_modules",
                ["q_proj", "v_proj", "k_proj", "o_proj"],
            ),
            "output_dir": str(output_dir / "output"),
            "num_epochs": cfg.get("num_epochs", 3),
            "micro_batch_size": cfg.get("micro_batch_size", 4),
            "gradient_accumulation_steps": cfg.get("gradient_accumulation_steps", 4),
            "learning_rate": cfg.get("learning_rate", 2e-5),
            "optimizer": cfg.get("optimizer", "adamw_torch"),
            "lr_scheduler": cfg.get("lr_scheduler", "cosine"),
            "warmup_steps": cfg.get("warmup_steps", 10),
            "bf16": cfg.get("bf16", True),
            "sequence_len": cfg.get("sequence_len", 4096),
        }

        # Write Axolotl YAML config
        config_path = output_dir / "axolotl_config.yml"
        try:
            import yaml
            config_path.write_text(
                yaml.dump(axolotl_config, default_flow_style=False),
                encoding="utf-8",
            )
        except ImportError:
            # Fallback: write as JSON if PyYAML not installed
            config_path = output_dir / "axolotl_config.json"
            config_path.write_text(
                json.dumps(axolotl_config, indent=2) + "\n",
                encoding="utf-8",
            )

        job = FinetuneJob(
            id=job_id,
            provider="local",
            model_base=base_model,
            training_file=str(path.resolve()),
            status=FinetuneStatus.PENDING,
            created_at=datetime.now(timezone.utc).isoformat(),
            metadata={
                "config_path": str(config_path),
                "output_dir": str(output_dir / "output"),
                "axolotl_config": axolotl_config,
            },
        )
        self._jobs.append(job)
        self._save_jobs()

        return FinetuneResult(
            job=job,
            message=(
                f"Axolotl config generated at {config_path}. "
                f"Run training with: accelerate launch -m axolotl.cli.train {config_path}"
            ),
        )

    # -- Status checking -------------------------------------------------------

    def check_status(self, job_id: str) -> FinetuneJob:
        """Check and update the status of a fine-tuning job.

        For OpenAI jobs, polls the API. For local jobs, checks if the
        output directory contains a completed model.
        """
        job = self._find_job(job_id)
        if job is None:
            raise ValueError(f"Job not found: {job_id}")

        if job.status in (
            FinetuneStatus.COMPLETED,
            FinetuneStatus.FAILED,
            FinetuneStatus.CANCELLED,
        ):
            return job

        if job.provider == "openai":
            self._poll_openai_status(job)
        elif job.provider == "local":
            self._check_local_status(job)

        self._save_jobs()
        return job

    def _poll_openai_status(self, job: FinetuneJob) -> None:
        """Poll OpenAI API for job status."""
        client = self._openai or _get_openai_client()
        if client is None:
            return

        openai_job_id = job.metadata.get("openai_job_id")
        if not openai_job_id:
            return

        try:
            resp = client.fine_tuning.jobs.retrieve(openai_job_id)
            status_map = {
                "validating_files": FinetuneStatus.UPLOADING,
                "queued": FinetuneStatus.TRAINING,
                "running": FinetuneStatus.TRAINING,
                "succeeded": FinetuneStatus.COMPLETED,
                "failed": FinetuneStatus.FAILED,
                "cancelled": FinetuneStatus.CANCELLED,
            }
            job.status = status_map.get(resp.status, job.status)
            if resp.status == "succeeded" and resp.fine_tuned_model:
                job.fine_tuned_model = resp.fine_tuned_model
            if resp.status == "failed":
                job.error = getattr(resp, "error", None) or "Training failed"
                if hasattr(job.error, "message"):
                    job.error = job.error.message
        except Exception as exc:
            logger.warning("Failed to poll OpenAI status for %s: %s", job.id, exc)

    def _check_local_status(self, job: FinetuneJob) -> None:
        """Check if local training output directory has completed artifacts."""
        output_dir = job.metadata.get("output_dir")
        if not output_dir:
            return

        output_path = Path(output_dir)
        # Check for common training completion markers
        adapter_markers = [
            "adapter_model.bin",
            "adapter_model.safetensors",
            "pytorch_model.bin",
            "model.safetensors",
        ]
        for marker in adapter_markers:
            if (output_path / marker).exists():
                job.status = FinetuneStatus.COMPLETED
                job.fine_tuned_model = str(output_path)
                return

    # -- Job listing -----------------------------------------------------------

    def list_jobs(self) -> list[FinetuneJob]:
        """Return all known fine-tuning jobs."""
        return list(self._jobs)

    # -- Model deployment ------------------------------------------------------

    def deploy(self, job_id: str) -> str:
        """Register a completed fine-tuned model in models.json and routing.json.

        Returns the model identifier that was registered.
        """
        job = self._find_job(job_id)
        if job is None:
            raise ValueError(f"Job not found: {job_id}")
        if job.status != FinetuneStatus.COMPLETED:
            raise ValueError(
                f"Cannot deploy job {job_id}: status is {job.status.value}, "
                f"expected 'completed'"
            )
        if not job.fine_tuned_model:
            raise ValueError(f"Job {job_id} has no fine_tuned_model set")

        model_id = job.fine_tuned_model

        # 1. Register in models.json
        self._register_model(model_id, job)

        # 2. Update routing.json if a ModelRouter is available
        if self._router is not None:
            self._update_routing(model_id, job)

        logger.info("Deployed fine-tuned model: %s", model_id)
        return model_id

    def _register_model(self, model_id: str, job: FinetuneJob) -> None:
        """Add model entry to ~/.saido_agent/models.json."""
        self._config_dir.mkdir(parents=True, exist_ok=True)
        models: dict[str, Any] = {}
        if self._models_file.exists():
            try:
                models = json.loads(self._models_file.read_text(encoding="utf-8"))
            except (json.JSONDecodeError, OSError):
                models = {}

        models[model_id] = {
            "base_model": job.model_base,
            "provider": job.provider,
            "training_file": job.training_file,
            "created_at": job.created_at,
            "job_id": job.id,
            "metadata": job.metadata,
        }
        self._models_file.write_text(
            json.dumps(models, indent=2) + "\n", encoding="utf-8"
        )

    def _update_routing(self, model_id: str, job: FinetuneJob) -> None:
        """Update the routing config to prefer the fine-tuned model for matching tasks.

        Adds a 'finetune' task entry pointing at the new model.
        """
        routing_cfg = self._router.routing_config
        routing = routing_cfg.setdefault("routing", {})
        domain = job.metadata.get("domain", "finetune")

        routing[domain] = {
            "prefer": "local" if job.provider == "local" else "cloud",
            "model": model_id,
        }
        self._router._save_routing_config()

    # -- A/B comparison testing ------------------------------------------------

    def compare(
        self,
        model_a: str,
        model_b: str,
        test_questions: list[str],
    ) -> dict:
        """Run the same questions against two models and compare quality.

        Returns a comparison report with per-question and aggregate metrics.
        """
        if not test_questions:
            raise ValueError("test_questions must be a non-empty list")

        results_a = self._run_model(model_a, test_questions)
        results_b = self._run_model(model_b, test_questions)

        comparisons = []
        for i, question in enumerate(test_questions):
            resp_a = results_a[i]
            resp_b = results_b[i]
            comparisons.append({
                "question": question,
                "model_a_response": resp_a,
                "model_b_response": resp_b,
                "model_a_length": len(resp_a),
                "model_b_length": len(resp_b),
                "model_a_coherence": self._score_coherence(resp_a),
                "model_b_coherence": self._score_coherence(resp_b),
            })

        avg_len_a = sum(c["model_a_length"] for c in comparisons) / len(comparisons)
        avg_len_b = sum(c["model_b_length"] for c in comparisons) / len(comparisons)
        avg_coh_a = sum(c["model_a_coherence"] for c in comparisons) / len(comparisons)
        avg_coh_b = sum(c["model_b_coherence"] for c in comparisons) / len(comparisons)

        return {
            "model_a": model_a,
            "model_b": model_b,
            "num_questions": len(test_questions),
            "comparisons": comparisons,
            "summary": {
                "avg_length_a": avg_len_a,
                "avg_length_b": avg_len_b,
                "avg_coherence_a": avg_coh_a,
                "avg_coherence_b": avg_coh_b,
            },
        }

    def _run_model(self, model: str, questions: list[str]) -> list[str]:
        """Run questions against a model via the client or router.

        Falls back to a placeholder if neither a client nor router is available.
        """
        responses: list[str] = []
        for question in questions:
            try:
                resp = self._call_model(model, question)
                responses.append(resp)
            except Exception as exc:
                logger.warning("Model %s failed on question: %s", model, exc)
                responses.append(f"[error] {exc}")
        return responses

    def _call_model(self, model: str, prompt: str) -> str:
        """Make an LLM call through the available provider infrastructure.

        This is a thin wrapper that can be overridden or mocked in tests.
        """
        # Try OpenAI-compatible endpoint for local/cloud models
        client = self._openai or _get_openai_client()
        if client is not None:
            try:
                resp = client.chat.completions.create(
                    model=model,
                    messages=[{"role": "user", "content": prompt}],
                    max_tokens=512,
                )
                return resp.choices[0].message.content or ""
            except Exception as exc:
                return f"[error] {exc}"

        return f"[unavailable] no client for model {model}"

    @staticmethod
    def _score_coherence(text: str) -> float:
        """Heuristic coherence score (0.0-1.0) based on basic text quality signals.

        This is a simple proxy -- real evaluation would use an LLM-as-judge.
        """
        if not text or text.startswith("[error]") or text.startswith("[unavailable]"):
            return 0.0

        score = 0.5  # baseline

        # Reward longer, more substantive responses
        word_count = len(text.split())
        if word_count > 20:
            score += 0.15
        if word_count > 50:
            score += 0.1

        # Reward sentence structure (periods, question marks)
        sentence_enders = sum(1 for c in text if c in ".!?")
        if sentence_enders >= 2:
            score += 0.1

        # Penalise very short or empty-feeling responses
        if word_count < 5:
            score -= 0.3

        return max(0.0, min(1.0, score))
